### ISSUE TITLE
Can't start fos_ctd

### ISSUE THREAD

**Issue by riccardorinaldi7** [eclipse-fog05/plugin-fdu-containerd#13]
Hi, trying to install and start the containerd plugin, the service fails. To install and run the plugin I cloned this repo, I ran `make` and then I ran `make install` but when I start the fos_ctd service with systemctl, it fails. Here's the error reported by `systemctl status fos_ctd`:
![systemctl_status_fos_ctd](https://user-images.githubusercontent.com/35295021/99987204-78da5280-2db0-11eb-9408-90a885de808b.png)

Then I tried manually: `sudo -u /etc/fos/plugins/plugin-fdu-containerd/containerd_plugin /etc/fos/plugins/plugin-fdu-containerd/containerd_plugin.json` but it gives me this error:
![fos_ctd_manuale](https://user-images.githubusercontent.com/35295021/99987380-ade6a500-2db0-11eb-98e5-05233ab549e5.png)

**Comment by gabrik** [comment]
Hi @riccardorinaldi7, you need to install the zenoh client library: https://github.com/eclipse-fog05/fog05/releases/download/v0.2.2/libzenoh-0.3.0-amd64.deb 

also be sure that contained is installed, if not you can install from this .deb file: https://github.com/eclipse-fog05/fog05/releases/download/v0.2.2/containerd.io_1.3.4-1_amd64.deb

**Comment by riccardorinaldi7** [comment]
Hi @gabrik, thanks for your reply. I installed both packages with `sudo dpkg -i <packagename>.deb` but the same error appears in the terminal (both systemctl and manual start)

**Comment by gabrik** [comment]
Can you post the output `ldd /etc/fos/plugins/plugin-fdu-container/container_plugin` ?

It seems that the library is not in the path.

**Comment by riccardorinaldi7** [comment]
![ldd_containerd](https://user-images.githubusercontent.com/35295021/100102111-6ec55c00-2e63-11eb-96c5-20867eb362c9.png)


You're right, the library is missing! How can i fix that problem?

**Comment by gabrik** [comment]
It is strange, but you need to add `/usr/local/lib` to your `LD_LIBRARY_PATH`

Just `sudo echo "LD_LIBARY_PATH=$LD_LIBARY_PATH:/usr/local/lib" >> /etc/environment.d/90-fos.conf`
You may need to restart the machine after this modification.

**Comment by riccardorinaldi7** [comment]
I restarted the virtual machine but it still doesn't work...
![zenolib not found](https://user-images.githubusercontent.com/35295021/100107846-63c1fa00-2e6a-11eb-8181-49556e4d058d.png)

I repeat my installation process so to make you better understand if I did something wrong:
- build.md: install opam 4.09.0 and all dependecies, then run `./build.sh`
- install.md: run `sudo make intall` inside fog05 cloned repo, install linuxbridge cloning the repo and running `sudo make install`, install lxd plugin cloning the repo, installing lxd/lxd-client dependencies and running `sudo make install`, install containerd cloning the repository, installing golang.go package and running `sudo make install`

Everything works fine except for the containerd plugin.

**Comment by gabrik** [comment]
My bad, I see now that there is a typo in the name of the env variable, the correct command is:
`sudo echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib" >> /etc/environment.d/90-fos.conf`

Also you do not need to install it from source, you should always use the latest release: https://github.com/eclipse-fog05/fog05/releases/tag/v0.2.2

**Comment by riccardorinaldi7** [comment]
Now `ldd` find the library but the plugin fails to start anyway
![ldd but not working](https://user-images.githubusercontent.com/35295021/100116059-96bcbb80-2e73-11eb-9493-5a297ed6e069.png)

 I don't attach a picture of systemctl's log because it's the same as before.

**Comment by gabrik** [comment]
That's odd.

Does `sudo ldd /etc/fos/plugins/plugin-fdu-container/container_plugin` see the library?
It may be that the export is not present in the `root` environment

**Comment by riccardorinaldi7** [comment]
> Does sudo ldd /etc/fos/plugins/plugin-fdu-container/container_plugin see the library?

No, sudo doesn't see the library. How can I fix the export?

**Comment by gabrik** [comment]
We can try to add it in `/etc/environment`

So adding this line `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib` to `/etc/environment` could work.

**Comment by riccardorinaldi7** [comment]
Now I get this error:
![Screenshot from 2020-11-24 17-58-02](https://user-images.githubusercontent.com/35295021/100126764-a988bd80-2e7e-11eb-8108-92a32b66e7d0.png)

**Comment by riccardorinaldi7** [comment]
Ok, now the service try to start but an exception arises:
![Screenshot from 2020-11-24 18-07-21](https://user-images.githubusercontent.com/35295021/100128023-0638a800-2e80-11eb-848c-03fb0f5347e8.png)

I definitively think that the root of my vm doesn't want me to graduate

**Comment by riccardorinaldi7** [comment]
I don't understand why there are so many problems related to users. This is a clean installation of ubuntu with a common user account

**Comment by gabrik** [comment]
Is the containerd service running? `systemctl status containerd`

**Comment by riccardorinaldi7** [comment]
Yes

![Screenshot from 2020-11-24 18-13-06](https://user-images.githubusercontent.com/35295021/100128587-bd352380-2e80-11eb-8496-917a50a29295.png)

**Comment by gabrik** [comment]
Try: `sudo usermod -aG docker root`

Which ubuntu version of ubuntu are you using?

**Comment by riccardorinaldi7** [comment]
The command 'usermod' seems to work but I'm still unable to run the fos_ctd service. The errors are the same as above.

I don't know if it was a mistake but when I installed the plugin, in the containerd_plugin.json the field "ylocator" was automatically set to a random address (192.168-style), I've changed it with 127.0.0.1 where my yaks server relied.

Version of Ubuntu: Ubuntu 20.04.1 LTS

**Comment by gabrik** [comment]
This last issue is not related with fog05, but for some reason seems that the containerd socket file has bad permissions.

We can try to `chmod` it to make it readable and writable from any one. 

`sudo chmod a+rw /run/containerd/containerd.sock`

**Comment by riccardorinaldi7** [comment]
Now it works! (but I had to set the 'x' option, too)

Thank you very much for the support

**Comment by riccardorinaldi7** [comment]
About this:
>Also you do not need to install it from source, you should always use the latest release: https://github.com/eclipse-fog05/fog05/releases/tag/v0.2.2

I suggest you to mention it in the install.md file.
Best.
