### ISSUE TITLE
[BUG] systemd service fails to start

### ISSUE THREAD

**Issue by marcogozzi** [eclipse-fog05/plugin-fdu-containerd#3]
The Makefile creates the directory `/etc/fos/plugins/containerd` whereas the systemd service `fos_ctd.service` tries executing the containerd plugin from the folder `/etc/fos/plugins/plugin-fdu-containerd`.

A solutions to this would be modifying the Makefile variable that stores the path from
`CTD_PLUGIN_DIR = /etc/fos/plugins/containerd`
to
`CTD_PLUGIN_DIR = /etc/fos/plugins/plugin-fdu-containerd`
 to keep the same naming convention as the other plugins.

**Comment by gabrik** [comment]
Thanks, @marcogozzi for reporting this.
 
Indeed it is just a typo in the Makefile.

We'll solve this ASAP.
